// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookReviewer.Models
{
    public partial class Author
    {
        public Author()
        {
            AuthorGenre = new HashSet<AuthorGenre>();
            BookAuthor = new HashSet<BookAuthor>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Bio { get; set; }

        public virtual ICollection<AuthorGenre> AuthorGenre { get; set; }
        public virtual ICollection<BookAuthor> BookAuthor { get; set; }
    }
}