// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookReviewer.Models
{
    public partial class Book
    {
        public Book()
        {
            BookAuthor = new HashSet<BookAuthor>();
            BookGenre = new HashSet<BookGenre>();
            BookReview = new HashSet<BookReview>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Description { get; set; }

        public virtual ICollection<BookAuthor> BookAuthor { get; set; }
        public virtual ICollection<BookGenre> BookGenre { get; set; }
        public virtual ICollection<BookReview> BookReview { get; set; }

        public static implicit operator List<object>(Book v)
        {
            throw new NotImplementedException();
        }
    }
}