// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookReviewer.Models
{
    public partial class BookReview
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public string Comment { get; set; }
        public int Rating { get; set; }

        public virtual Book Book { get; set; }
    }
}