// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookReviewer.Models
{
    public partial class Genre
    {
        public Genre()
        {
            AuthorGenre = new HashSet<AuthorGenre>();
            BookGenre = new HashSet<BookGenre>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<AuthorGenre> AuthorGenre { get; set; }
        public virtual ICollection<BookGenre> BookGenre { get; set; }
    }
}